# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: xsap.net
email: ysm@xsap.net
description: >- # this means to ignore newlines until "baseurl:"
  NxNote is an AI-powered knowledge management platform for SAP professionals. 
  Built by a team with 20+ years of SAP experience, it integrates AI email writing, 
  secure local knowledge storage, SAP workflow visualization, and smart login management 
  to help enterprises boost efficiency and reduce costs.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nxnote.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: nxnote
github_username:  nxnote

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
jsonld: |
    {
      "@context": "https://schema.org",
      "@type": "SoftwareApplication",
      "name": "NXNote",
      "alternateName": "XSAP Note",
      "applicationCategory": "BusinessApplication",
      "applicationSubCategory": "Knowledge Management",
      "operatingSystem": "Windows",
      "softwareVersion": "2.0",
      "datePublished": "2025-10-24",
      "programmingLanguage": "Dart",
      "url": "https://xsap.net",
      "image": "https://xsap.net/assets/images/nxxii.png",
      "description": "NXNote is a professional AI-powered knowledge management software for SAP experts, designed to organize SAP documentation, process diagrams, project plans, and intelligent workflows. It integrates seamlessly with SAP systems and AI-driven email automation.",
      "publisher": {
        "@type": "Organization",
        "name": "Shanghai Niaoxun Information Technology Co., Ltd.",
        "url": "https://nxxii.com",
        "sameAs": [
          "https://www.wikidata.org/wiki/Q136653173",
          "https://github.com/nxnote",
          "https://xsap.net"
        ],
        "logo": "https://xsap.net/assets/images/nxxii.png"
      },
      "offers": {
        "@type": "Offer",
        "price": "20",
        "priceCurrency": "USD",
        "availability": "https://schema.org/InStock"
      }
    }
